// This file is auto-generated by @hey-api/openapi-ts

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $NodeIn = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/NodeIn'
            },
            type: 'array',
            title: 'Children'
        }
    },
    type: 'object',
    required: ['title', 'children'],
    title: 'NodeIn'
} as const;

export const $NodeOut = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        rank: {
            type: 'string',
            title: 'Rank'
        },
        depth: {
            type: 'integer',
            title: 'Depth'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    required: ['id', 'rank', 'depth', 'title'],
    title: 'NodeOut'
} as const;

export const $Page = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NodeOut'
            },
            type: 'array',
            title: 'Data'
        },
        cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cursor'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'Page'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;