// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ChildrenOfApiChildrenNodeIdGetData, ChildrenOfApiChildrenNodeIdGetResponse, InsertTreeApiTreePostData, InsertTreeApiTreePostResponse } from './types.gen';

/**
 * Children Of
 * @param data The data for the request.
 * @param data.nodeId
 * @returns NodeOut Successful Response
 * @throws ApiError
 */
export const childrenOfApiChildrenNodeIdGet = (data: ChildrenOfApiChildrenNodeIdGetData): CancelablePromise<ChildrenOfApiChildrenNodeIdGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/children/{node_id}',
    path: {
        node_id: data.nodeId
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Insert Tree
 * @param data The data for the request.
 * @param data.requestBody
 * @param data.insertBefore
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const insertTreeApiTreePost = (data: InsertTreeApiTreePostData): CancelablePromise<InsertTreeApiTreePostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/tree',
    query: {
        insert_before: data.insertBefore
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };