// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetTreeApiTreeGetData, GetTreeApiTreeGetResponse, InsertTreeApiTreePostData, InsertTreeApiTreePostResponse } from './types.gen';

/**
 * Get Tree
 * @param data The data for the request.
 * @param data.beforeCursor
 * @param data.afterCursor
 * @param data.limit
 * @returns Page Successful Response
 * @throws ApiError
 */
export const getTreeApiTreeGet = (data: GetTreeApiTreeGetData = {}): CancelablePromise<GetTreeApiTreeGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/tree',
    query: {
        before_cursor: data.beforeCursor,
        after_cursor: data.afterCursor,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Insert Tree
 * @param data The data for the request.
 * @param data.requestBody
 * @param data.insertBefore
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const insertTreeApiTreePost = (data: InsertTreeApiTreePostData): CancelablePromise<InsertTreeApiTreePostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/tree',
    query: {
        insert_before: data.insertBefore
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };