// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LimitOffsetPage_NodeOut_ = {
    items: Array<NodeOut>;
    total: number | null;
    limit: number | null;
    offset: number | null;
};

export type NodeIn = {
    title: string;
    children: Array<NodeIn>;
};

export type NodeOut = {
    id: number;
    rank: string;
    depth: number;
    title: string | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetTreeApiTreeGetData = {
    /**
     * Page size limit
     */
    limit?: number;
    /**
     * Page offset
     */
    offset?: number;
};

export type GetTreeApiTreeGetResponse = LimitOffsetPage_NodeOut_;

export type InsertTreeApiTreePostData = {
    insertBefore?: number | null;
    requestBody: NodeIn;
};

export type InsertTreeApiTreePostResponse = unknown;

export type DeleteNodeApiNodeNodeIdDeleteData = {
    nodeId: number;
};

export type DeleteNodeApiNodeNodeIdDeleteResponse = unknown;

export type UpdateNodeApiNodeNodeIdPutData = {
    moveBefore: number | null;
    nodeId: number;
};

export type UpdateNodeApiNodeNodeIdPutResponse = unknown;

export type $OpenApiTs = {
    '/api/tree': {
        get: {
            req: GetTreeApiTreeGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: LimitOffsetPage_NodeOut_;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: InsertTreeApiTreePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/node/{node_id}': {
        delete: {
            req: DeleteNodeApiNodeNodeIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: UpdateNodeApiNodeNodeIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};