// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NodeIn = {
    title: string;
    children: Array<NodeIn>;
};

export type NodeOut = {
    id: number;
    rank: string;
    depth: number;
    title: string | null;
};

export type Page = {
    data: Array<NodeOut>;
    before_cursor?: string | null;
    after_cursor?: string | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetTreeApiTreeGetData = {
    afterCursor?: string | null;
    beforeCursor?: string | null;
    limit?: number;
};

export type GetTreeApiTreeGetResponse = Page;

export type InsertTreeApiTreePostData = {
    insertBefore?: number | null;
    requestBody: NodeIn;
};

export type InsertTreeApiTreePostResponse = unknown;

export type GetCountApiTreeCountGetResponse = number;

export type DeleteNodeApiNodeNodeIdDeleteData = {
    nodeId: number;
};

export type DeleteNodeApiNodeNodeIdDeleteResponse = unknown;

export type UpdateNodeApiNodeNodeIdPutData = {
    moveBefore: number | null;
    nodeId: number;
};

export type UpdateNodeApiNodeNodeIdPutResponse = unknown;

export type $OpenApiTs = {
    '/api/tree': {
        get: {
            req: GetTreeApiTreeGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: Page;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: InsertTreeApiTreePostData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/tree/count': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: number;
            };
        };
    };
    '/api/node/{node_id}': {
        delete: {
            req: DeleteNodeApiNodeNodeIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: UpdateNodeApiNodeNodeIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};