"""create tree table

Revision ID: 5d750fd2953d
Revises: 
Create Date: 2024-08-13 16:40:08.485528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d750fd2953d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('start_id', sa.Integer(), nullable=True),
    sa.Column('has_children', sa.Boolean(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['start_id'], ['tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_rank'), 'tree', ['rank'], unique=True)
    op.create_index(op.f('ix_tree_start_id'), 'tree', ['start_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tree_start_id'), table_name='tree')
    op.drop_index(op.f('ix_tree_rank'), table_name='tree')
    op.drop_table('tree')
    # ### end Alembic commands ###
