"""create tree table

Revision ID: 8352a03a55b0
Revises: 
Create Date: 2024-06-11 16:02:46.247910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from unitree.models import Rational

# revision identifiers, used by Alembic.
revision: str = '8352a03a55b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left', Rational(), nullable=False),
    sa.Column('right', Rational(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_left'), 'tree', ['left'], unique=False)
    op.create_index(op.f('ix_tree_right'), 'tree', ['right'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tree_right'), table_name='tree')
    op.drop_index(op.f('ix_tree_left'), table_name='tree')
    op.drop_table('tree')
    # ### end Alembic commands ###
