"""create tree table

Revision ID: beaa5c0343ba
Revises: 3b07894533a6
Create Date: 2024-06-17 11:53:47.658867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from unitree.models import Rational

# revision identifiers, used by Alembic.
revision: str = 'beaa5c0343ba'
down_revision: Union[str, None] = '3b07894533a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fraction', Rational(), nullable=False),
    sa.Column('start_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['start_id'], ['tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_fraction'), 'tree', ['fraction'], unique=False)
    op.create_index(op.f('ix_tree_start_id'), 'tree', ['start_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tree_start_id'), table_name='tree')
    op.drop_index(op.f('ix_tree_fraction'), table_name='tree')
    op.drop_table('tree')
    # ### end Alembic commands ###
