"""create tree table

Revision ID: d08043d09c51
Revises: 
Create Date: 2024-06-11 19:05:52.631904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from unitree.models import Rational

# revision identifiers, used by Alembic.
revision: str = 'd08043d09c51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left_key', Rational(), nullable=False),
    sa.Column('right_key', Rational(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_left_key'), 'tree', ['left_key'], unique=False)
    op.create_index(op.f('ix_tree_right_key'), 'tree', ['right_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tree_right_key'), table_name='tree')
    op.drop_index(op.f('ix_tree_left_key'), table_name='tree')
    op.drop_table('tree')
    # ### end Alembic commands ###
